import {
  Wrench,
  Droplet,
  Brush,
  Truck,
  Scissors,
  Hammer,
  Laptop,
  Dog,
  Leaf,
  ShieldCheck,
  Camera,
  Paintbrush,
} from "lucide-react"
import type { ServiceType } from "./types"

export const services: ServiceType[] = [
  {
    id: 1,
    name: "Eletricista",
    icon: Wrench,
    description: "Serviços de instalação e reparo elétrico",
    startingPrice: 80,
    keywords: ["elétrica", "tomada", "fiação", "curto-circuito", "instalação"],
  },
  {
    id: 2,
    name: "Encanador",
    icon: Droplet,
    description: "Serviços de encanamento e hidráulica",
    startingPrice: 90,
    keywords: ["vazamento", "cano", "água", "torneira", "hidráulica"],
  },
  {
    id: 3,
    name: "Diarista",
    icon: Brush,
    description: "Limpeza residencial e comercial",
    startingPrice: 120,
    keywords: ["limpeza", "faxina", "casa", "apartamento", "escritório"],
  },
  {
    id: 4,
    name: "Fretes",
    icon: Truck,
    description: "Transporte de móveis e objetos",
    startingPrice: 100,
    keywords: ["mudança", "transporte", "carreto", "entrega", "móveis"],
  },
  {
    id: 5,
    name: "Cabeleireiro",
    icon: Scissors,
    description: "Cortes e tratamentos capilares",
    startingPrice: 60,
    keywords: ["cabelo", "corte", "penteado", "coloração", "barba"],
  },
  {
    id: 6,
    name: "Pedreiro",
    icon: Hammer,
    description: "Construção e reformas",
    startingPrice: 150,
    keywords: ["obra", "reforma", "construção", "alvenaria", "parede"],
  },
  {
    id: 7,
    name: "Informática",
    icon: Laptop,
    description: "Suporte técnico e manutenção",
    startingPrice: 70,
    keywords: ["computador", "notebook", "formatação", "vírus", "software"],
  },
  {
    id: 8,
    name: "Pet Sitter",
    icon: Dog,
    description: "Cuidados com animais de estimação",
    startingPrice: 50,
    keywords: ["cachorro", "gato", "passeio", "banho", "tosa"],
  },
  {
    id: 9,
    name: "Jardinagem",
    icon: Leaf,
    description: "Manutenção de jardins e áreas verdes",
    startingPrice: 100,
    keywords: ["jardim", "plantas", "grama", "poda", "paisagismo"],
  },
  {
    id: 10,
    name: "Segurança",
    icon: ShieldCheck,
    description: "Instalação de sistemas de segurança",
    startingPrice: 200,
    keywords: ["alarme", "câmera", "monitoramento", "cerca", "proteção"],
  },
  {
    id: 11,
    name: "Fotógrafo",
    icon: Camera,
    description: "Serviços fotográficos profissionais",
    startingPrice: 250,
    keywords: ["foto", "evento", "ensaio", "casamento", "aniversário"],
  },
  {
    id: 12,
    name: "Pintor",
    icon: Paintbrush,
    description: "Pintura residencial e comercial",
    startingPrice: 120,
    keywords: ["pintura", "parede", "teto", "textura", "reforma"],
  },
]
